name: generator

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - name: generat chinaese readme
        uses: eryajf/yaml-readme@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          pattern: 'items/*/*.yaml'
          template: 'template/README.tpl'
          output: 'README.md'
          username: "github-actions[bot]"
          org: eryajf
          repo: awesome-ops
          sortby: '!zh'
          groupby: kind
          header: false
      - name: generat english readme
        uses: eryajf/yaml-readme@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          pattern: 'items/*/*.yaml'
          username: "github-actions[bot]"
          org: eryajf
          repo: awesome-ops
          sortby: '!zh'
          groupby: kind
          header: false
          template: 'template/README-en.tpl'
          output: 'resources/README-en.md'